/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ResourceLazyImport = createFileRoute('/$resource')()
const ResourceIdLazyImport = createFileRoute('/$resource/$id')()

// Create/Update Routes

const ResourceLazyRoute = ResourceLazyImport.update({
  path: '/$resource',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$resource.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResourceIdLazyRoute = ResourceIdLazyImport.update({
  path: '/$resource/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$resource_.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$resource': {
      id: '/$resource'
      path: '/$resource'
      fullPath: '/$resource'
      preLoaderRoute: typeof ResourceLazyImport
      parentRoute: typeof rootRoute
    }
    '/$resource/$id': {
      id: '/$resource/$id'
      path: '/$resource/$id'
      fullPath: '/$resource/$id'
      preLoaderRoute: typeof ResourceIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ResourceLazyRoute,
  ResourceIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$resource",
        "/$resource/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$resource": {
      "filePath": "$resource.lazy.tsx"
    },
    "/$resource/$id": {
      "filePath": "$resource_.$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
